enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


[mode.main.binding]
# i3 wraps focus by default
alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down --boundaries all-monitors-outer-frame'
alt-k = 'focus up --boundaries all-monitors-outer-frame'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

alt-right = 'workspace next'
alt-left = 'workspace prev'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-g = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion'               # 'layout stacking' in i3
alt-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-q = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

ctrl-alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
ctrl-alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
ctrl-alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
ctrl-alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'
ctrl-alt-shift-5 = 'move-node-to-workspace --focus-follows-window 5'
ctrl-alt-shift-6 = 'move-node-to-workspace --focus-follows-window 6'
ctrl-alt-shift-7 = 'move-node-to-workspace --focus-follows-window 7'
ctrl-alt-shift-8 = 'move-node-to-workspace --focus-follows-window 8'
ctrl-alt-shift-9 = 'move-node-to-workspace --focus-follows-window 9'
ctrl-alt-shift-0 = 'move-node-to-workspace --focus-follows-window 10'

ctrl-alt-h = 'move-workspace-to-monitor left'
ctrl-alt-j = 'move-workspace-to-monitor down'
ctrl-alt-k = 'move-workspace-to-monitor up'
ctrl-alt-l = 'move-workspace-to-monitor right'

alt-shift-c = 'reload-config'

alt-shift-r = 'mode resize'

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# [gaps]
# inner.horizontal = 3
# inner.vertical = 3
# outer.left = 3
# outer.bottom = 3
# outer.top = 3
# outer.right = 3

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
check-further-callbacks = true
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
check-further-callbacks = true
run = ['move-node-to-workspace 8']

[[on-window-detected]]
if.app-id = 'com.gitbutler.app'
check-further-callbacks = true
run = ['move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
check-further-callbacks = true
run = ['move-node-to-workspace 10']